clear
clc
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\giova\Downloads\ENGE 1216\FinalDesignData.txt
%
% Auto-generated by MATLAB on 27-Apr-2022 15:14:02

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["R", "V", "RPM"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Dataset = readmatrix('FinalDesignData.txt');

%% Convert to output type
R = Dataset(:,1);
V = Dataset(:,2);
RPM = Dataset(:,3);





%% Clear temporary variables
clear opts tbl


%% creates a power dataset.
P = 1:28;

%% initializes the varible that will be used as a counter.
i = 1;

Cp = 1:28;

%% In this while loop the power will be calculated from the voltage vector and the resistance vector.
while i <= length(V)
    P(i) = V(i)^2 / R(i);
    Cp(i) = ( 2 * P(i) / (1.225 * (3.8)^3 * 4));
    
    i = i + 1;
end

%% gathers the data from the while loop and finds the average value.
avgPower = mean(P);
%% these two calls print out our power calculation from our data gathered.
disp("The average power of our wind turbine is:")
disp(avgPower + " watts")
%% this calculates the power effiecency from the results
avgEfficiency = mean(Cp);

%% displays the power efficiency on the console. 
disp("The power coefficient of our wind turbine is:")
disp(avgEfficiency)

